import { createRepo, pushFilesToRepo, generateRepoName } from '@/lib/github'

export async function POST(request: Request) {
  const body = await request.json()
  const { siteName, description, files, password } = body

  if (password !== process.env.FACTORY_PASSWORD) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  if (!siteName || !files || !Array.isArray(files)) {
    return new Response(JSON.stringify({ error: 'siteName and files required' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  const repoName = generateRepoName(siteName)

  // Step 1: Create the repo
  const createResult = await createRepo(repoName, description || siteName)
  if (!createResult.success) {
    return Response.json({ success: false, error: createResult.error })
  }

  // Small delay to let GitHub initialise
  await new Promise((r) => setTimeout(r, 2000))

  // Step 2: Push all files
  const pushResult = await pushFilesToRepo(
    repoName,
    files,
    `Initial build — generated by Site Factory`
  )

  if (!pushResult.success) {
    return Response.json({
      success: false,
      error: pushResult.error,
      repoUrl: createResult.repoUrl,
      note: 'Repo created but file push failed. Push manually.',
    })
  }

  return Response.json({
    success: true,
    repoName,
    repoUrl: createResult.repoUrl,
    fileCount: files.length,
  })
}
